# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=150)),
                ('art_text', models.TextField()),
                ('art_date', models.DateTimeField()),
                ('art_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
